<?php

namespace Database\Seeders;

use App\Models\PricingPackage;
use Illuminate\Database\Seeder;

class PricingPackageSeeder extends Seeder
{
    public function run(): void
    {
        $categories = \App\Models\PricingCategory::all()->pluck('id', 'name_en')->toArray();

        $packages = [
            [
                'name' => 'Starter Website',
                'name_en' => 'Starter Website',
                'name_ar' => 'موقع ويب للمبتدئين',
                'category' => PricingPackage::CATEGORY_WEB,
                'category_en' => PricingPackage::CATEGORY_WEB,
                'category_ar' => 'حلول الويب',
                'pricing_category_id' => $categories['Web Solutions'] ?? 1,
                'price' => 'Starting from $299',
                'features' => [
                    'Responsive website',
                    'Contact form',
                    'WhatsApp integration',
                    'Basic SEO',
                    'Mobile-friendly design',
                    '14 days support included',
                ],
                'features_en' => [
                    'Responsive website',
                    'Contact form',
                    'WhatsApp integration',
                    'Basic SEO',
                    'Mobile-friendly design',
                    '14 days support included',
                ],
                'features_ar' => [
                    'موقع ويب متجاوب',
                    'نموذج اتصال',
                    'تكامل واتساب',
                    'تحسين محركات البحث الأساسي',
                    'تصميم متوافق مع الجوال',
                    'دعم لمدة 14 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'Business Website + Dashboard',
                'name_en' => 'Business Website + Dashboard',
                'name_ar' => 'موقع ويب للأعمال + لوحة تحكم',
                'category' => PricingPackage::CATEGORY_WEB,
                'category_en' => PricingPackage::CATEGORY_WEB,
                'category_ar' => 'حلول الويب',
                'pricing_category_id' => $categories['Web Solutions'] ?? 1,
                'price' => 'Starting from $999',
                'features' => [
                    'Multi-page website',
                    'Admin dashboard',
                    'Authentication system',
                    'API integration',
                    'CMS/content management',
                    'Analytics/dashboard',
                    'Responsive design',
                    '30 days support included',
                ],
                'features_en' => [
                    'Multi-page website',
                    'Admin dashboard',
                    'Authentication system',
                    'API integration',
                    'CMS/content management',
                    'Analytics/dashboard',
                    'Responsive design',
                    '30 days support included',
                ],
                'features_ar' => [
                    'موقع ويب متعدد الصفحات',
                    'لوحة تحكم للمسؤول',
                    'نظام المصادقة',
                    'تكوين واجهة برمجة التطبيقات',
                    'نظام إدارة المحتوى',
                    'التحليلات/لوحة القيادة',
                    'تصميم متجاوب',
                    'دعم لمدة 30 يومًا',
                ],
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'Complete Digital Solution',
                'name_en' => 'Complete Digital Solution',
                'name_ar' => 'حل رقمي كامل',
                'category' => PricingPackage::CATEGORY_WEB,
                'category_en' => PricingPackage::CATEGORY_WEB,
                'category_ar' => 'حلول الويب',
                'pricing_category_id' => $categories['Web Solutions'] ?? 1,
                'price' => 'Starting from $3,000+',
                'features' => [
                    'Website',
                    'Online dashboard',
                    'Advanced APIs',
                    'Business automation',
                    'Multi-user system',
                    'Reporting system',
                    'Cloud-ready architecture',
                    '60 days support included',
                ],
                'features_en' => [
                    'Website',
                    'Online dashboard',
                    'Advanced APIs',
                    'Business automation',
                    'Multi-user system',
                    'Reporting system',
                    'Cloud-ready architecture',
                    '60 days support included',
                ],
                'features_ar' => [
                    'موقع ويب',
                    'لوحة تحكم عبر الإنترنت',
                    'واجهات برمجة تطبيقات متقدمة',
                    'أتمتة الأعمال',
                    'نظام متعدد المستخدمين',
                    'نظام التقارير',
                    'بنية جاهزة للسحابة',
                    'دعم لمدة 60 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
            ],
            [
                'name' => 'Starter Mobile App',
                'name_en' => 'Starter Mobile App',
                'name_ar' => 'تطبيق جوال للمبتدئين',
                'category' => PricingPackage::CATEGORY_MOBILE,
                'category_en' => PricingPackage::CATEGORY_MOBILE,
                'category_ar' => 'تطبيقات الجوال',
                'pricing_category_id' => $categories['Mobile Applications'] ?? 2,
                'price' => 'Starting from $699',
                'features' => [
                    'Flutter app',
                    'Authentication',
                    'API integration',
                    'Android support',
                    'Modern UI',
                    '14 days support included',
                ],
                'features_en' => [
                    'Flutter app',
                    'Authentication',
                    'API integration',
                    'Android support',
                    'Modern UI',
                    '14 days support included',
                ],
                'features_ar' => [
                    'تطبيق Flutter',
                    'المصادقة',
                    'تكوين واجهة برمجة التطبيقات',
                    'دعم Android',
                    'واجهة مستخدم حديثة',
                    'دعم لمدة 14 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 4,
            ],
            [
                'name' => 'Business Mobile App',
                'name_en' => 'Business Mobile App',
                'name_ar' => 'تطبيق جوال للأعمال',
                'category' => PricingPackage::CATEGORY_MOBILE,
                'category_en' => PricingPackage::CATEGORY_MOBILE,
                'category_ar' => 'تطبيقات الجوال',
                'pricing_category_id' => $categories['Mobile Applications'] ?? 2,
                'price' => 'Starting from $1,500',
                'features' => [
                    'Advanced Flutter app',
                    'Dashboard integration',
                    'Push notifications',
                    'APIs',
                    'User management',
                    'Modern UI/UX',
                    '30 days support included',
                ],
                'features_en' => [
                    'Advanced Flutter app',
                    'Dashboard integration',
                    'Push notifications',
                    'APIs',
                    'User management',
                    'Modern UI/UX',
                    '30 days support included',
                ],
                'features_ar' => [
                    'تطبيق Flutter متقدم',
                    'تكامل لوحة التحكم',
                    'الإشعارات الفورية',
                    'واجهات برمجة التطبيقات',
                    'إدارة المستخدمين',
                    'واجهة مستخدم/تجربة مستخدم حديثة',
                    'دعم لمدة 30 يومًا',
                ],
                'is_featured' => true,
                'is_active' => true,
                'order' => 5,
            ],
            [
                'name' => 'Full Mobile + Web Platform',
                'name_en' => 'Full Mobile + Web Platform',
                'name_ar' => 'منصة جوال + ويب كاملة',
                'category' => PricingPackage::CATEGORY_MOBILE,
                'category_en' => PricingPackage::CATEGORY_MOBILE,
                'category_ar' => 'تطبيقات الجوال',
                'pricing_category_id' => $categories['Mobile Applications'] ?? 2,
                'price' => 'Starting from $4,000+',
                'features' => [
                    'Flutter app',
                    'Website',
                    'Online dashboard',
                    'Cloud sync',
                    'APIs',
                    'Notifications',
                    'Admin management',
                    '60 days support included',
                ],
                'features_en' => [
                    'Flutter app',
                    'Website',
                    'Online dashboard',
                    'Cloud sync',
                    'APIs',
                    'Notifications',
                    'Admin management',
                    '60 days support included',
                ],
                'features_ar' => [
                    'تطبيق Flutter',
                    'موقع ويب',
                    'لوحة تحكم عبر الإنترنت',
                    'مزامنة السحابة',
                    'واجهات برمجة التطبيقات',
                    'الإشعارات',
                    'إدارة المسؤول',
                    'دعم لمدة 60 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 6,
            ],
            [
                'name' => 'Local POS System',
                'name_en' => 'Local POS System',
                'name_ar' => 'نظام نقاط البيع المحلي',
                'category' => PricingPackage::CATEGORY_POS,
                'category_en' => PricingPackage::CATEGORY_POS,
                'category_ar' => 'نقاط البيع والأنظمة التجارية',
                'pricing_category_id' => $categories['POS & Business Systems'] ?? 3,
                'price' => 'Starting from $1,200',
                'features' => [
                    'Point of sale system',
                    'Barcode scanning',
                    'Receipt printing',
                    'Basic inventory tracking',
                    'Daily sales reports',
                    'Multi-currency support',
                    '14 days support included',
                ],
                'features_en' => [
                    'Point of sale system',
                    'Barcode scanning',
                    'Receipt printing',
                    'Basic inventory tracking',
                    'Daily sales reports',
                    'Multi-currency support',
                    '14 days support included',
                ],
                'features_ar' => [
                    'نظام نقاط البيع',
                    'مسح الباركود',
                    'طباعة الإيصالات',
                    'تتبع المخزون الأساسي',
                    'تقارير المبيعات اليومية',
                    'دعم العملات المتعددة',
                    'دعم لمدة 14 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 7,
            ],
            [
                'name' => 'POS + Stock Management',
                'name_en' => 'POS + Stock Management',
                'name_ar' => 'نظام نقاط البيع + إدارة المخزون',
                'category' => PricingPackage::CATEGORY_POS,
                'category_en' => PricingPackage::CATEGORY_POS,
                'category_ar' => 'نقاط البيع والأنظمة التجارية',
                'pricing_category_id' => $categories['POS & Business Systems'] ?? 3,
                'price' => 'Starting from $2,500',
                'features' => [
                    'Advanced POS system',
                    'Full stock management',
                    'Low stock alerts',
                    'Supplier management',
                    'Purchase orders',
                    'Sales analytics',
                    'Multi-branch support',
                    '30 days support included',
                ],
                'features_en' => [
                    'Advanced POS system',
                    'Full stock management',
                    'Low stock alerts',
                    'Supplier management',
                    'Purchase orders',
                    'Sales analytics',
                    'Multi-branch support',
                    '30 days support included',
                ],
                'features_ar' => [
                    'نظام نقاط البيع المتقدم',
                    'إدارة المخزون الكاملة',
                    'تنبيهات انخفاض المخزون',
                    'إدارة الموردين',
                    'طلبات الشراء',
                    'تحليلات المبيعات',
                    'دعم الفروع المتعددة',
                    'دعم لمدة 30 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 8,
            ],
            [
                'name' => 'Full Accounting & ERP System',
                'name_en' => 'Full Accounting & ERP System',
                'name_ar' => 'نظام محاسبة و ERP كامل',
                'category' => PricingPackage::CATEGORY_POS,
                'category_en' => PricingPackage::CATEGORY_POS,
                'category_ar' => 'نقاط البيع والأنظمة التجارية',
                'pricing_category_id' => $categories['POS & Business Systems'] ?? 3,
                'price' => 'Starting from $5,000+',
                'features' => [
                    'Complete ERP solution',
                    'Full accounting module',
                    'Financial reporting',
                    'Payroll management',
                    'Tax management',
                    'Budget planning',
                    'Multi-company support',
                    '60 days support included',
                ],
                'features_en' => [
                    'Complete ERP solution',
                    'Full accounting module',
                    'Financial reporting',
                    'Payroll management',
                    'Tax management',
                    'Budget planning',
                    'Multi-company support',
                    '60 days support included',
                ],
                'features_ar' => [
                    'حل ERP كامل',
                    'وحدة محاسبة كاملة',
                    'التقارير المالية',
                    'إدارة الرواتب',
                    'إدارة الضرائب',
                    'تخطيط الميزانية',
                    'دعم الشركات المتعددة',
                    'دعم لمدة 60 يومًا',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 9,
            ],
            [
                'name' => 'Basic Maintenance',
                'name_en' => 'Basic Maintenance',
                'name_ar' => 'الصيانة الأساسية',
                'category' => PricingPackage::CATEGORY_SUPPORT,
                'category_en' => PricingPackage::CATEGORY_SUPPORT,
                'category_ar' => 'الدعم والصيانة',
                'pricing_category_id' => $categories['Support & Maintenance'] ?? 4,
                'price' => '$50/month',
                'features' => [
                    'Bug fixes',
                    'Security updates',
                    'Monthly backups',
                    'Email support',
                    'Performance monitoring',
                    'Minor updates',
                ],
                'features_en' => [
                    'Bug fixes',
                    'Security updates',
                    'Monthly backups',
                    'Email support',
                    'Performance monitoring',
                    'Minor updates',
                ],
                'features_ar' => [
                    'إصلاح الأخطاء',
                    'تحديثات الأمان',
                    'نسخ احتياطي شهري',
                    'دعم البريد الإلكتروني',
                    'مراقبة الأداء',
                    'تحديثات ثانوية',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 10,
            ],
            [
                'name' => 'Business Maintenance',
                'name_en' => 'Business Maintenance',
                'name_ar' => 'صيانة الأعمال',
                'category' => PricingPackage::CATEGORY_SUPPORT,
                'category_en' => PricingPackage::CATEGORY_SUPPORT,
                'category_ar' => 'الدعم والصيانة',
                'pricing_category_id' => $categories['Support & Maintenance'] ?? 4,
                'price' => '$150/month',
                'features' => [
                    'Priority bug fixes',
                    'Security patches',
                    'Weekly backups',
                    'Phone & email support',
                    'Performance optimization',
                    'Feature updates',
                    'SSL certificate renewal',
                    'Monthly reports',
                ],
                'features_en' => [
                    'Priority bug fixes',
                    'Security patches',
                    'Weekly backups',
                    'Phone & email support',
                    'Performance optimization',
                    'Feature updates',
                    'SSL certificate renewal',
                    'Monthly reports',
                ],
                'features_ar' => [
                    'إصلاح الأخطاء الأولوية',
                    'تصحيحات الأمان',
                    'نسخ احتياطي أسبوعي',
                    'دعم الهاتف والبريد الإلكتروني',
                    'تحسين الأداء',
                    'تحديثات الميزات',
                    'تجديد شهادة SSL',
                    'تقارير شهرية',
                ],
                'is_featured' => true,
                'is_active' => true,
                'order' => 11,
            ],
            [
                'name' => 'Enterprise Support',
                'name_en' => 'Enterprise Support',
                'name_ar' => 'دعم المؤسسات',
                'category' => PricingPackage::CATEGORY_SUPPORT,
                'category_en' => PricingPackage::CATEGORY_SUPPORT,
                'category_ar' => 'الدعم والصيانة',
                'pricing_category_id' => $categories['Support & Maintenance'] ?? 4,
                'price' => 'Custom Quote',
                'features' => [
                    '24/7 dedicated support',
                    'Immediate bug fixes',
                    'Daily backups with off-site storage',
                    'Dedicated account manager',
                    'Full system audits',
                    'Custom development',
                    'SLA guarantees',
                    'Training sessions',
                ],
                'features_en' => [
                    '24/7 dedicated support',
                    'Immediate bug fixes',
                    'Daily backups with off-site storage',
                    'Dedicated account manager',
                    'Full system audits',
                    'Custom development',
                    'SLA guarantees',
                    'Training sessions',
                ],
                'features_ar' => [
                    'دعم مخصص 24/7',
                    'إصلاح فوري للأخطاء',
                    'نسخ احتياطي يومي مع تخزين خارج الموقع',
                    'مدير حساب مخصص',
                    'تدقيق كامل للنظام',
                    'تطوير مخصص',
                    'ضمانات SLA',
                    'جلسات تدريب',
                ],
                'is_featured' => false,
                'is_active' => true,
                'order' => 12,
            ],
        ];

        PricingPackage::query()->delete();

        foreach ($packages as $package) {
            PricingPackage::create($package);
        }
    }
}
